### ISSUE TITLE
下载不了qcloud_cos模块

### ISSUE THREAD

**Issue by feiaaa1** [WeChatAPIs/WechatBotCMD#5]
![屏幕截图 2024-04-19 130718](https://github.com/WeChatAPIs/WechatBotCMD/assets/143931158/ef218d23-b821-4dfa-8ce5-1926293b8e1e)

**Comment by WeChatAPIs** [comment]
This library is non-essential and generally not needed. You can delete the relevant code or run `pip install -U cos-python-sdk-v5`.
