### ISSUE TITLE
计算机积极拒绝

### ISSUE THREAD

**Issue by 1404577549** [WeChatAPIs/WechatBotCMD#6]
<img width="876" alt="436f3c2ab85cd2374acd59e36a2c68b" src="https://github.com/WeChatAPIs/WechatBotCMD/assets/167504509/cb2a0d33-237b-4439-aae4-cf8ce69d44d9">

**Comment by WeChatAPIs** [comment]
Please review the readme again and follow the steps to initiate the startup process.
